### PR TITLE
Force using IPv4 when the machine supports IPv6 networks

### PR DESCRIPTION
**Pull request by punchagan**
Instagram seems to be ignoring connections coming from IPv6 networks, and
the scraper does not run when running on machines with IPv6 support. This
commit makes ensures that the scraper is using IPv4 connections.

### CODE REVIEW

**Comment by VasiliPupkin256** [comment]
But instagram works just fine over IPv6 in the browser. What error do you get?

**Comment by punchagan** [comment]
`ERROR: Error getting user details for <username>. Please verify that the user exists.`

**Comment by punchagan** [comment]
Thanks for merging this and making a release too, @rarcega! :tada:

**Comment by VasiliPupkin256** [comment]
@punchagan I've checked it on IPv6 machine and scraper works just fine. I've even disabled IPv4 completely. It must be a problem in your network setup.

**Pull request merged**
