### PR TITLE
Update Instagram version in STORIES_UA

### PR DESCRIPTION
**Pull request by AlexNik**
Fix issue https://github.com/rarcega/instagram-scraper/issues/453
#453 

Now it can download IGTV like a regular video (with key -t video).

### CODE REVIEW

**Comment by reliefs** [comment]
We also have problems with --profile-data, could something like this also be the issue for that ?

**Comment by AlexNik** [comment]
@reliefs which problems?
Do you have example?

**Comment by reliefs** [comment]
Thanks for your reply, yes here is an example on the issue.
https://github.com/rarcega/instagram-scraper/issues/449

**Comment by AlexNik** [comment]
@reliefs I've check #449 and it works fine without this PR.
You have to get successfull login.
If it fails you can't get profile metadata.

**Pull request merged**
