### PR TITLE
continue on "HTTPError 410"

### PR DESCRIPTION
**Pull request by florinbarbisch**
HTTPError 410 means that the URL is gone (in this case the media has been deleted). And since the media will never comeback it does not make any sense to retry again.

Fixes: #343

### CODE REVIEW

**Comment by VasiliPupkin256** [comment]
In the issue description you've told that the error appear on multiple accounts, I doubt that it somehow repeatedly stuck on a media deleted just in time of scrape operation. I've never seen this before during two years of usage. It is more likely that the error is caused by wrong url parsing or something like that and the media can still be downloaded. Can you reproduce the error on those accounts?

Ignore of a particular response code can be done more easily on the line 992 without the need of exception processing

**Comment by VasiliPupkin256** [comment]
And `continue` statement in this loop wont skip the media, it will retry on it again

**Comment by florinbarbisch** [comment]
Thanks for the feedback and taking your time to review this. So I will close this issue and do further research before I create a new pull request.

**Comment by VasiliPupkin256** [comment]
The issue is valid, there was no need to close it. Just find a way to reproduce it on those profiles or give them  to us here

**Pull request closed without merging**
