### PR TITLE
Support Usage Without Logging In

### PR DESCRIPTION
**Pull request by hamishdh**
Support using the scraper without logging in via the "--no-login" (or "--no_login" or "-nl"); this is False by default. If a username & password are also specified they will be ignored.

Any private user's media will be unavailable; additionally Stories and High Resolution profile pictures are unavailable (HTTP 403 on these requests). Everything else seems to works as expected.

### CODE REVIEW

**Comment by VasiliPupkin256** [comment]
What is the point of providing username and password but not logging in?

**Comment by hamishdh** [comment]
The intended usage is not to supply a username and password if the '--no-login' argument is specified; If you do then they are ignored.
Could update the behaviour to crash or do the login anyway; I don't feel strongly about the behaviour in those cases.

**Comment by VasiliPupkin256** [comment]
If a user wants a login he specify username, if he don't need a login he doesn't specify username. What is the point of this switch?

**Comment by hamishdh** [comment]
The point of the switch was to avoid changing the default behaviour of the program. Thinking about this now it makes sense to have no-login as the default behaviour if no username/PW supplied and remove the switch entirely

**Comment by VasiliPupkin256** [comment]
The scraper didn't require login before, the mandatory login was added in one bugfix, not sure if it was needed at the time or it was also a bug. The requirement can probably be relaxed if it doesn't need anymore.

**Comment by hcotel** [comment]
I guess same request limits(200/h) are valid for guest login. We can overcome it on user login with many users, is there a way for it in guest_login ?

**Pull request merged**
