### PR TITLE
Get live video / broadcast

### LINKED ISSUE #74: Live Replays downloads
instagram_private_api_extensions recently added support for downloading IG Live Replays. This recent IG feature is described at http://blog.instagram.com/post/162048719842/160720-replay-live-stories

Can this be utilized in instagram-scraper ?

### PR DESCRIPTION
**Pull request by AlexNik**
Closes #74

### CODE REVIEW

**Comment by AlexNik** [comment]
@rarcega What I should to do with Python 3.4 & 3.5?
It seems like "moviepy" lib depends on "imageio" and it has bug with dependencies for Python 3.4 and 3.5.

**Comment by Aaronzinhoo** [comment]
The mantainer seems to be inactive. Should we fork this and start a new repo?

**Comment by AlexNik** [comment]
@Aaronzinhoo I think we sholud wait a little more.

**Comment by Aaronzinhoo** [comment]
@AlexNik I agree, I am sure he will pull through for all the people using this awesome program

**Pull request merged**
